name: ft-transcendence

services:
  web:
    build:
      context: "./web/"
    container_name: web
    restart: unless-stopped
    ports:
      - "${DEV_HTTP_PORT:-80}:8080"
      - "${DEV_HTTPS_PORT:-443}:8443"
    networks:
      - ft-transcendence-net
    environment:
      DOMAIN: ${DOMAIN:-}
      SCHEME: ${SCHEME:-}
      PROD: ${PROD:-0}
    # volumes: # commented out because in web/Dockerfile, we already copy the dist folder
    #   - "./web/dist:/srv/:rw"
    develop:
      watch: # will reload caddy when changing Caddyfile.template in the host system
        - path: ./web/Caddyfile.template
          action: rebuild
          target: /etc/caddy/Caddyfile.template

networks:
  ft-transcendence-net:
    driver: bridge
