name: ft-transcendence

services:
  web:
    build:
      context: "./web/"
    container_name: web
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:8080"
      - "${HTTPS_PORT:-443}:8443"
    networks:
      - ft-transcendence-net
    volumes:
      - "caddy_data:/srv/.local/share/caddy/"
    environment:
      - DOMAIN=${DOMAIN:?Error, DOMAIN environment variable must be set (e.g. in .env)}
      - SCHEME=${SCHEME:?Error, SCHEME environment variable must be set (e.g. in .env)}
    develop:
      watch: # will reload caddy when changing Caddyfile in the host system
        - path: ./web/Caddyfile
          action: rebuild
          target: /etc/caddy/Caddyfile

  backend:
    build:
      context: "./backend/"
    container_name: backend
    restart: unless-stopped
    networks:
      - ft-transcendence-net
    environment:
      - NODE_ENV=development
      - BACKEND_PORT=${BACKEND_PORT:-3000}
    volumes:
      - ./backend/data:/app/data/

volumes:
  caddy_data:

networks:
  ft-transcendence-net:
    driver: bridge
