name: ft-transcendence

services:
  caddy-coraza:
    build:
      context: "./caddy-coraza/"
    container_name: caddy-coraza
    restart: unless-stopped
    ports:
      - "${DEV_HTTP_PORT:-80}:8080"
      - "${DEV_HTTPS_PORT:-443}:8443"
    environment:
      DOMAIN: ${DOMAIN:-}
      SCHEME: ${SCHEME:-}
      PROD: ${PROD:-0}
    develop:
      watch: # will reload caddy when changing Caddyfile.template in the host system
        - path: ./caddy-coraza/Caddyfile.template
          action: rebuild
          target: /etc/caddy/Caddyfile.template
