name: ft-transcendence

services:
    caddy:
        build: "./caddy/"
        container_name: caddy
        restart: unless-stopped
        ports:
            - "${HTTP_PORT:-8080}:8080"
            - "${HTTPS_PORT:-8443}:8443"
        networks:
            - ft-transcendence-net
        volumes:
            - "caddy_data:/srv/.local/share/caddy/"
            - "./app/dist/:/srv/app/:ro"
        environment:
            - "DOMAINS=${DOMAINS:-localhost}"
            - "CADDY_EXTRA_GLOBAL_DIRECTIVES=${CADDY_EXTRA_GLOBAL_DIRECTIVES:-}"
            - "CADDY_EXTRA_SITE_DIRECTIVES=${CADDY_EXTRA_SITE_DIRECTIVES:-}"
            - "BACKEND_PORT=${BACKEND_PORT:-3000}"
        develop:
            watch:
                - path: "./caddy/Caddyfile"
                  action: rebuild
                  target: "/etc/caddy/Caddyfile"
        env_file:
          - .env
          - config.env
    app:
      build: "./app/"
      container_name: app
      restart: unless-stopped
      volumes:
        - "./app/dist/:/app/dist/:ro"
      env_file:
        - .env
        - config.env

    backend:
        build:
            context: "./backend/"
        container_name: backend
        restart: unless-stopped
        networks:
            - ft-transcendence-net
        environment:
            - "NODE_ENV=development"
            - "BACKEND_PORT=${BACKEND_PORT:-3000}"
            - "DB_PATH=${DB_PATH:-}"
            - "JWT_SECRET=${JWT_SECRET:-}"
        volumes:
            - "drizzle:/app/drizzle/"
        env_file:
            - .env
            - config.env

volumes:
    caddy_data:
    drizzle:

networks:
    ft-transcendence-net:
        driver: bridge
