---
name: ft-transcendence

# https://github.com/docker/compose/pull/5140
x-watch-common: &watch-common
    WATCH: ${WATCH:-0}

x-env-common: &env-common
    <<: *watch-common
    BACKEND_PORT: ${BACKEND_PORT:-3000}

x-env-files: &env-files
    - .env
    - config.env

services:
    caddy:
        build: "./caddy/"
        container_name: caddy
        restart: unless-stopped
        ports:
            - "${HTTP_PORT:-8080}:8080"
            - "${HTTPS_PORT:-8443}:8443"
        networks:
            - ft-transcendence-net
        volumes:
            - "caddy_data:/frontend/.local/share/caddy/"
            - "frontend:/frontend/dist/:ro"
            # - "public:/frontend/src/public/:ro"
        environment:
            <<: *env-common
            DOMAINS: ${DOMAINS:-localhost}
            CADDY_EXTRA_GLOBAL_DIRECTIVES: ${CADDY_EXTRA_GLOBAL_DIRECTIVES:-}
            CADDY_EXTRA_SITE_DIRECTIVES: ${CADDY_EXTRA_SITE_DIRECTIVES:-}
        develop:
            watch:
                - path: "./caddy/Caddyfile"
                  action: sync
                  target: "/etc/caddy/Caddyfile"
        env_file: *env-files

    frontend:
        build: "./frontend/"
        container_name: frontend
        restart: no
        ports:
            - "35729:35729" # Live-reload port
        environment: *watch-common
        volumes:
            - "frontend:/frontend/dist/"
        develop:
            watch:
                - path: "./frontend/"
                  action: sync # Might fail on MacOS when node_modules is touched, use `rebuild' as fallback
                  target: "/frontend/"
                - path: "./frontend/package.json"
                  action: rebuild
                  target: "/frontend/package.json"
                - path: "./frontend/esbuild.config.js"
                  action: rebuild
                  target: "/frontend/esbuild.config.js"
                - path: "./frontend/reload-server.js"
                  action: rebuild
                  target: "/frontend/reload-server.js"
        env_file: *env-files

    backend:
        build: "./backend/"
        container_name: backend
        restart: unless-stopped
        networks:
            - ft-transcendence-net
        environment:
            <<: *env-common
            NODE_ENV: ${NODE_ENV:-development}
            DB_PATH: ${DB_PATH:-}
            JWT_SECRET: ${JWT_SECRET:-}
        volumes:
            - "drizzle:/backend/drizzle/"
        develop:
            watch:
                - path: "./backend/"
                  action: sync # Might fail on MacOS when node_modules is touched, use `rebuild' as fallback
                  target: "/backend/"
                - path: "./backend/package.json"
                  action: rebuild
                  target: "/backend/package.json"
                - path: "./backend/esbuild.config.js"
                  action: rebuild
                  target: "/backend/esbuild.config.js"
        env_file: *env-files

volumes:
    caddy_data:
    drizzle:
    frontend:

networks:
    ft-transcendence-net:
        driver: bridge
