name: ft-transcendence

services:
  web:
    build:
      context: "./web/"
    container_name: web
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:?Error, HTTP_PORT environment variable must be set (see Makefile)}:8080"
      - "${HTTPS_PORT:?Error, HTTPS_PORT environment variable must be set (see Makefile)}:8443"
    networks:
      - ft-transcendence-net
    volumes:
      - "caddy_data:/srv/.local/share/caddy/"
    environment:
      - DOMAINS=${DOMAINS:?Error, DOMAINS environment variable must be set (see Makefile)}
    develop:
      watch: # will reload caddy when changing Caddyfile in the host system
        - path: ./web/Caddyfile
          action: rebuild
          target: /etc/caddy/Caddyfile

  backend:
    build:
      context: "./backend/"
    container_name: backend
    restart: unless-stopped
    networks:
      - ft-transcendence-net
    environment:
      - NODE_ENV=development
      - BACKEND_PORT=${BACKEND_PORT:?Error, BACKEND_PORT environment variable must be set (see .env)}
      - DB_PATH=/app/backend/drizzle/db.sqlite # Will probably move later
      - JWT_SECRET=${JWT_SECRET:-}
    volumes:
      - ./backend/drizzle:/app/backend/drizzle

volumes:
  caddy_data:

networks:
  ft-transcendence-net:
    driver: bridge
