---
name: ft-transcendence

# https://github.com/docker/compose/pull/5140
x-env-watch: &env-watch
    WATCH: "${WATCH:-0}"

x-env-caddy-backend: &env-caddy-backend
    <<: *env-watch
    BACKEND_PORT: "${BACKEND_PORT:-3000}"
    DOMAINS: "${DOMAINS:-localhost}"

x-env-files: &env-files
    - config.env

services:
    caddy:
        build: "./caddy/"
        container_name: caddy
        restart: unless-stopped
        ports:
            - "${HTTP_PORT:-8080}:8080"
            - "${HTTPS_PORT:-8443}:8443"
        networks:
            ft-transcendence-net:
                ipv4_address: &caddy-ip 10.42.42.1
        volumes:
            - "caddy-data:/frontend/.local/share/caddy/"
            - "frontend:/frontend/dist/:ro"
        environment:
            <<: *env-caddy-backend
            CADDY_EXTRA_GLOBAL_DIRECTIVES: "${CADDY_EXTRA_GLOBAL_DIRECTIVES:-}"
            CADDY_EXTRA_SITE_DIRECTIVES: "${CADDY_EXTRA_SITE_DIRECTIVES:-}"
        depends_on:
            - frontend
            - backend
        develop:
            watch:
                - path: "./caddy/Caddyfile"
                  action: sync
                  target: "/etc/caddy/Caddyfile"
        env_file: *env-files

    frontend:
        build: "./frontend/"
        container_name: frontend
        restart: no
        ports:
            - "35729:35729" # Live-reload port
        environment: *env-watch
        volumes:
            - "frontend:/frontend/dist/"
        develop:
            watch:
                - path: "./frontend/"
                  action: sync # Might fail on MacOS when node_modules is touched, use `rebuild' as fallback
                  target: "/frontend/"
                - path: "./frontend/package.json"
                  action: rebuild
                  target: "/frontend/package.json"
                - path: "./frontend/esbuild.config.js"
                  action: rebuild
                  target: "/frontend/esbuild.config.js"
                - path: "./frontend/reload-server.js"
                  action: rebuild
                  target: "/frontend/reload-server.js"
        env_file: *env-files

    backend:
        build: "./backend/"
        container_name: backend
        restart: unless-stopped
        networks:
            ft-transcendence-net:
                ipv4_address: &backend-ip 10.42.42.2
        environment:
            <<: *env-caddy-backend
            NODE_ENV: "${NODE_ENV:-development}"
            DB_PATH: "${DB_PATH:-}"
            LOGSTASH_HOST: "logstash"
            LOGSTASH_PORT: "5000"
        volumes:
            - "drizzle:/backend/drizzle/"
            - "./.secrets/backend_vault_token:/run/secrets/backend_vault_token"
        depends_on:
            vault:
                restart: true
                condition: service_healthy
            logstash:
                restart: true
                condition: service_healthy
        develop:
            watch:
                - path: "./backend/"
                  action: sync # Might fail on MacOS when node_modules is touched, use `rebuild' as fallback
                  target: "/backend/"
                - path: "./backend/package.json"
                  action: rebuild
                  target: "/backend/package.json"
                - path: "./backend/esbuild.config.js"
                  action: rebuild
                  target: "/backend/esbuild.config.js"
        env_file: *env-files

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
        container_name: elasticsearch
        environment:
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
            discovery.type: "single-node"
            xpack.security.enabled: "false"
        volumes:
            - "elasticsearch-data:/usr/share/elasticsearch/data/"
        ports:
            - "9200:9200"
        networks:
            ft-transcendence-net:
                ipv4_address: &elasticsearch-ip 10.42.42.3
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:9200"]
            interval: 30s
            timeout: 10s
            retries: 5

    logstash:
        image: docker.elastic.co/logstash/logstash:8.17.3
        container_name: logstash
        volumes:
            - "./elk/logstash/pipeline/:/usr/share/logstash/pipeline/"
            - "./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro"
        ports:
            - "5000:5000/tcp"
            - "5000:5000/udp"
            - "9600:9600" # Logstash API port for health checking
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            ft-transcendence-net:
                ipv4_address: &logstash-ip 10.42.42.4
        depends_on:
            elasticsearch:
              condition: service_healthy
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:9600/_node/stats"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s

    kibana:
        image: docker.elastic.co/kibana/kibana:8.17.3
        container_name: kibana
        ports:
            - "5601:5601"
        environment:
            ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
        networks:
            ft-transcendence-net:
                ipv4_address: &kibana-ip 10.42.42.5
        depends_on:
            elasticsearch:
                condition: service_healthy
        restart: unless-stopped

    vault:
        build: "./vault/"
        container_name: vault
        restart: unless-stopped
        networks:
            ft-transcendence-net:
                ipv4_address: &vault_ip 10.42.42.42
        extra_hosts:
            backend: *backend-ip
            caddy: *caddy-ip
            elasticsearch: *elasticsearch-ip
            logstash: *logstash-ip
            kibana: *kibana-ip
        cap_add:
            - IPC_LOCK
        volumes:
            - "vault:/vault/file/"
            - "vault-secret:/vault/secret/"
            - "vault-logs:/vault/logs/"
            - "./.secrets/backend_vault_token:/run/secrets/backend_vault_token"
        environment:
            LOGLEVEL: "debug"
            SAVE_UNSEAL_KEYS: "1"
            SAVE_ROOT_TOKEN: "1"
        tty: true
        develop:
            watch:
                - path: "./vault/entrypoint.sh"
                  action: sync+restart
                  target: "/entrypoint.sh"
                - path: "./vault/replace_json_templates.py"
                  action: sync+restart
                  target: "/replace_json_templates.py"
                - path: "./vault/healthcheck.sh"
                  action: sync+restart
                  target: "/healthcheck.sh"
                - path: "./vault/config.hcl"
                  action: sync+restart
                  target: "/vault/config/config.hcl"
                - path: "./vault/env.json"
                  action: sync+restart
                  target: "/vault/config/env.json"
                - path: "./vault/policies/"
                  action: sync+restart
                  target: "/vault/policies/"

volumes:
    vault:
    vault-secret:
    vault-logs:
    caddy-data:
    drizzle:
    frontend:
    elasticsearch-data:

networks:
    ft-transcendence-net:
        enable_ipv6: false
        driver: bridge
        ipam:
              driver: default
              config:
                  - subnet: 10.42.42.0/24
                    ip_range: 10.42.42.0/24
                    gateway: 10.42.42.254
