# Server settings
server.name: kibana
server.host: "0.0.0.0"
server.port: 5601
server.ssl.enabled: false

# Elasticsearch connection
elasticsearch.hosts: ["https://elasticsearch:9200"]
elasticsearch.requestTimeout: 30000
elasticsearch.username: "${KIBANA_USER}"
elasticsearch.password: "${KIBANA_PASSWORD}"
elasticsearch.ssl.verificationMode: none

# Monitoring
monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true

# Security settings
xpack.encryptedSavedObjects.encryptionKey: "On0wtWLem6X9zPqflgMZLErS0uBAP1TxK2C/61aVtN8="
xpack.security.encryptionKey: "EwjRVSiLReWe8evzfUuUqkNwHoEU8FKgGvPoak6L/PA="
xpack.reporting.encryptionKey: "DLJa1ntjYc6SsJvkUa9Kqawqkm+jksn/4pOR9EQOlGQ="
