http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

# Pipeline settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Queue settings
queue.type: persisted
queue.max_bytes: 1gb

# Logging settings
log.level: info

# Performance settings
config.reload.automatic: true
config.reload.interval: 3s
